### ISSUE TITLE
How to extract features for a large program

### ISSUE THREAD

**Issue by twang15** [ctuning/reproduce-milepost-project#5]
I have difficulty in extract features for a benchmark with many files, since the tutorial here only tells me how to do this on  a per-function basis for a single file.

So I decide to record the solution I will find out here for others' benefit.
Here we go!

**Comment by twang15** [comment]
The first problem is 

the ctuning c++ compiler does not get installed after I follow the tutorial:

$ ck pull repo:reproduce-milepost-project
$ ck install package:compiler-gcc-4.4.4-milepost-src-deps
$ ck install package:compiler-ctuning-cc-2.5-plugins-src
$ ck install package:compiler-ctuning-cc-2.5-src

The question is: is there a c++ version? If so, how to install it?

**Comment by twang15** [comment]
I read this ck tutorial, https://michel.steuwer.info/About-CK/.
It gives me certain idea on how ck works, especially when compared to [spack](https://github.com/spack/spack).

BTW, spack documentation is much better, IMHO.

**Comment by twang15** [comment]
Running cTuning-cc as following, I found that g++ was not configured to be compiled. So the solution is to find a way to reconfigure MILEPOST GCC package with c++ support.
$ /home/twang15/CK-TOOLS/gcc-milepost-4.4.4-linux-64/bin/gcc -v
Using built-in specs.
Target: x86_64-unknown-linux-gnu
Configured with: ../milepost-gcc-4.4.4/configure --prefix=/home/twang15/CK-TOOLS/gcc-milepost-4.4.4-linux-64 --enable-languages=c,fortran --disable-multilib --with-gmp=/home/twang15/CK-TOOLS/gmp-5.0.5-linux-64 --with-mpfr=/home/twang15/CK-TOOLS/mpfr-3.1.0-linux-64 --with-mpc=
Thread model: posix
gcc version 4.4.4 (GCC)

**Comment by twang15** [comment]
Somehow, I realize that MILEPOST GCC and its dependent libraries are under ~/CK/reproduce-milepost-project/package/, and every package has a process.sh file, which is used for configure/make/install. 

Thus, I modify the following file to enable c++ so as to have g++ compiled.

CK/reproduce-milepost-project/package/compiler-gcc-4.4.4-milepost-src-deps/process.sh, line 91

Before modification:  EXTRA_CFG=" --enable-languages=c,fortran"
After modification: EXTRA_CFG=" --enable-languages=c,c++,fortran"

**Comment by twang15** [comment]
The ck tutorial https://michel.steuwer.info/About-CK/ somehow enlightens me that I should use the following command to avoid rebuild all MILEPOST GCC dependent libraries, and instead only rebuild MILEPOST GCC.

ck install package:compiler-gcc-4.4.4-milepost-src-deps rebuild=yes

**Comment by twang15** [comment]
The result is that I can find g++ compiled and installed under ~/CK-TOOLS/gcc-milepost-4.4.4-linux-64/bin/.

$ ls CK-TOOLS/gcc-milepost-4.4.4-linux-64/bin/
c++  g++  gccbug  gfortran                      x86_64-unknown-linux-gnu-g++  x86_64-unknown-linux-gnu-gcc-4.4.4
cpp  gcc  gcov    x86_64-unknown-linux-gnu-c++  x86_64-unknown-linux-gnu-gcc  x86_64-unknown-linux-gnu-gfortran

**Comment by twang15** [comment]
Next, I will try g++ compiler out and see whether it works properly.

#change directory to the code sample
cd \`ck find demo:ctuning-cc\`

**Comment by twang15** [comment]
Now, the next step is to replace the original c++ compiler with ~/CK-TOOLS/gcc-milepost-4.4.4-linux-64/bin/g++ .

This process is facilitated by the fact that there is an example: (under ~/CK/reproduce-milepost-project/demo/ctuning-cc)

_use_ctuning_cc_directly_extract_features.sh

It shows me how to set up the environment variables and realize the compiler drop-in step.

ck set env tags=compiler,ctuning-cc bat_file=tmp-ck-env.sh --bat_new --print && . ./tmp-ck-env.sh && CXX="$CK_CXX" CXXFLAGS="${args[@]}" make -j2

**Comment by twang15** [comment]
Finally, it works!

**Comment by twang15** [comment]
This is a painful process.
This pain can be greatly alleviated if documents can be improved with more examples.

Any way, thanks a lot for contributing MILEPOST GCC and CK!

**Comment by gfursin** [comment]
Hi @twang15 - I am sorry that you had so many issues with g++ or extracting features from larger programs. 

Based on your feedback I updated MILEPOST readme which now provides info about how to build milepost g++, how to extract milepost features and record them to JSON file and how to use CK virtual environment: 

* https://github.com/ctuning/reproduce-milepost-project#low-level-usage
* https://github.com/ctuning/reproduce-milepost-project#high-level-usage-ck-workflows

Also feel free to provide your own improvements to the CK modules - my point to release MILEPOST in the CK format is to let the community enhance it even if I don't work on this project anymore, or to take advantage of enhancements in other high-level CK workflows (such as "program" module).

Thank you very much for your interest and feedback - hope MILEPOST will be useful for your R&D!
