### ISSUE TITLE
Failure to extract features for c++ programs

### ISSUE THREAD

**Issue by twang15** [ctuning/reproduce-milepost-project#6]
There are error messages while extracting features of a c++ program.
E.g., 

ML-FEAT-PROC Error (2): Error consulting featuresall.P: unrecoverable_error/++Error[XSB/Runtime/P]: [Unrecoverable!]
++Memory violation occurred during evaluation.
++Please report this problem using the XSB bug tracking system accessible from
++     http://sourceforge.net/projects/xsb
++Please supply the steps necessary to reproduce the bug.
SourceForge
XSB
Download XSB for free. Logic Programming and Deductive Database system (Tabled Prolog) for Unix and Windows.
[featuresall compiled, cpu time used: 1.0250 seconds]
ML-FEAT-PROC Error (2): Error consulting featuresall.P: misc_error/++Error[XSB/Runtime/P]: [Miscellaneous] [Error in loading file ,./featuresall.xwam]
ML-FEAT-PROC Error: Query Error: existence_error/++Error[XSB/Runtime/P]: [Existence (No procedure :(usermod,/(fn_bb_nr,2)) exists)]

**Comment by twang15** [comment]
Also, not every function has a corresponding *.ft (feature file), which may be caused by the above error.

**Comment by twang15** [comment]
It may be caused by concurrent access to certain files when invoking multiple g++ instance with make -jN, where N is >= 2.

Using single compilation thread can indeed eliminate the above error message.

**Comment by gfursin** [comment]
Good point and thanks for reporting! I added notes to readme: https://github.com/ctuning/reproduce-milepost-project#notes . By the way, this is yet another motivation to implement feature aggregation inside GCC/LLVM plugins rather than external Prolog files ...
