### ISSUE TITLE
Error on extract feactures on docker

### ISSUE THREAD

**Issue by clappis** [ctuning/reproduce-milepost-project#8]
Run the README command on a new docker container.

$ ck pull repo:ctuning-programs
$ ck pipeline program:cbench-automotive-susan --speed --milepost --no_run --milepost_out_file=extracted-features.json

$ cd `ck find program:cbench-automotive-susan`
$ cd tmp
$ cat extracted-features.json

The files on tmp directory:
drwxr-xr-x 2 root root   4096 Oct 25 23:16 .
-rw-r--r-- 1 root root     41 Oct 25 23:16 a.out.git_hash
-rw-r--r-- 1 root root     36 Oct 25 23:16 a.out.md5
-rw-r--r-- 1 root root      0 Oct 25 23:16 null
-rw-r--r-- 1 root root 357799 Oct 25 23:16 a.out.dump
-rwxr-xr-x 1 root root  43472 Oct 25 23:16 a.out
-rw-r--r-- 1 root root  40224 Oct 25 23:16 susan.o
-rw-r--r-- 1 root root 120829 Oct 25 23:16 tmp-deps.json
drwxr-xr-x 1 root root   4096 Oct 25 23:16 ..

Looks like the null value should be the json file.

**Comment by gfursin** [comment]
Thanks for reporting - I will try to check it within a few days (now traveling). Will keep in touch.

**Comment by clappis** [comment]
Ok, I test in my native linux and works fine!

**Comment by gfursin** [comment]
Hi @clappis - the Docker image was indeed outdated and the problem was fixed in recent CK modules. I also fixed a minor issue with a "null" file. I also updated the Docker image so everything should work now. Thanks a lot for reporting!!!

**Comment by clappis** [comment]
Nice @gfursin ! 
I sent a message in your email about another subject, if you can answer me, it would be great

**Comment by gfursin** [comment]
Hmm, I actually didn't see it. Which email address did you use? Can you please resend it to grigori.fursin@cTuning.org ? Thanks!

**Comment by clappis** [comment]
I think that is your personal e-mail, but I sended for this one now, thanks a lot

**Comment by gfursin** [comment]
Sure, got your email. BTW, it's not a problem to use my personal e-mail, but there are just too many notification messages from GitHub, and many of them end up in spam, so I just didn't notice it ;) ...
